name: test_drive
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
   sdk: flutter

  cupertino_icons: ^1.0.6
  device_preview: ^1.1.0
  flutter_switch: ^0.3.2
  tab_container: ^2.0.0
  file_picker: ^8.0.0+1
  video_player: ^2.8.6
  assets_audio_player: ^3.1.1

dev_dependencies:
  flutter_test: 
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/audio/yo.mp3
  - assets/video/here.mp4


